// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/analytics" | "/admin/security" | "/admin/system" | "/admin/users" | "/education" | "/login" | "/maintenance" | "/projects" | "/projects/[projectId]" | "/s/[shareId]" | "/settings"
type AppRouteHandlerRoutes = "/api/auth/chutes/callback" | "/api/e2e/project" | "/api/git" | "/api/git/diff" | "/api/jobs/cancel" | "/api/jobs/execute" | "/api/lsp" | "/api/providers/catalog" | "/api/providers/chutes/test" | "/api/providers/openai-compatible/refresh-models" | "/api/providers/openai-compatible/test" | "/api/search" | "/api/search/replace"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/projects/[projectId]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/analytics": {}
  "/admin/security": {}
  "/admin/system": {}
  "/admin/users": {}
  "/api/auth/chutes/callback": {}
  "/api/e2e/project": {}
  "/api/git": {}
  "/api/git/diff": {}
  "/api/jobs/cancel": {}
  "/api/jobs/execute": {}
  "/api/lsp": {}
  "/api/providers/catalog": {}
  "/api/providers/chutes/test": {}
  "/api/providers/openai-compatible/refresh-models": {}
  "/api/providers/openai-compatible/test": {}
  "/api/search": {}
  "/api/search/replace": {}
  "/education": {}
  "/login": {}
  "/maintenance": {}
  "/projects": {}
  "/projects/[projectId]": { "projectId": string; }
  "/s/[shareId]": { "shareId": string; }
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/projects/[projectId]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
