// Generated by Convex during build - this is a stub for development
// Run `bunx convex dev` to generate the actual API

import type { DataModel } from "./dataModel";

// API structure matching Convex exports
export const api = {
  jobs: {
    list: "jobs/list" as const,
    get: "jobs/get" as const,
    streamLogs: "jobs/streamLogs" as const,
    create: "jobs/create" as const,
    createAndExecute: "jobs/createAndExecute" as const,
    updateStatus: "jobs/updateStatus" as const,
    appendLog: "jobs/appendLog" as const,
    cancel: "jobs/cancel" as const,
    remove: "jobs/remove" as const,
    cleanupOldJobs: "jobs/cleanupOldJobs" as const,
  },
  jobsExecution: {
    execute: "jobsExecution/execute" as const,
    executeHttp: "jobsExecution/executeHttp" as const,
  },
  files: {
    list: "files/list" as const,
    get: "files/get" as const,
    getByPath: "files/getByPath" as const,
    batchGet: "files/batchGet" as const,
    upsert: "files/upsert" as const,
    remove: "files/remove" as const,
    createSnapshot: "files/createSnapshot" as const,
    listSnapshots: "files/listSnapshots" as const,
  },
  projects: {
    list: "projects/list" as const,
    get: "projects/get" as const,
    create: "projects/create" as const,
    update: "projects/update" as const,
    remove: "projects/remove" as const,
  },
  chats: {
    list: "chats/list" as const,
    get: "chats/get" as const,
    create: "chats/create" as const,
    update: "chats/update" as const,
    remove: "chats/remove" as const,
    clearMessages: "chats/clearMessages" as const,
  },
  messages: {
    list: "messages/list" as const,
    get: "messages/get" as const,
    create: "messages/create" as const,
    remove: "messages/remove" as const,
  },
  artifacts: {
    list: "artifacts/list" as const,
    get: "artifacts/get" as const,
    create: "artifacts/create" as const,
    update: "artifacts/update" as const,
    updateStatus: "artifacts/updateStatus" as const,
    remove: "artifacts/remove" as const,
  },
  settings: {
    get: "settings/get" as const,
    upsert: "settings/upsert" as const,
    updateProviderConfig: "settings/updateProviderConfig" as const,
    remove: "settings/remove" as const,
  },
  llm: {
    chat: "llm/chat" as const,
    chatStream: "llm/chatStream" as const,
  },
};

export const internal = {
  jobs: {
    updateStatus: "internal/jobs/updateStatus" as const,
  },
};
