// Generated by Convex during build - this is a stub for development
// Run `bunx convex dev` to generate the actual types

export type Id<T extends string> = string & { __tableName: T };

export interface DataModel {
  users: { _id: Id<"users"> };
  projects: { _id: Id<"projects"> };
  files: { _id: Id<"files"> };
  fileSnapshots: { _id: Id<"fileSnapshots"> };
  chats: { _id: Id<"chats"> };
  messages: { _id: Id<"messages"> };
  artifacts: { _id: Id<"artifacts"> };
  settings: { _id: Id<"settings"> };
  jobs: { _id: Id<"jobs"> };
}
