// Generated by Convex during build - this is a stub for development
// Run `bunx convex dev` to generate the actual server types

export function query<T>(args: T): T {
  return args;
}

export function mutation<T>(args: T): T {
  return args;
}

export function action<T>(args: T): T {
  return args;
}

export function httpAction<T>(args: T): T {
  return args;
}
